project: 
  type: website
  output-dir: docs
  preview:
    port: 4200


website:
  title: "iA"
  navbar:
    background: primary
    search: true
    left:
      - text: "Page d'accueil"
        href: index.qmd
      - text: Postes
        menu:
          - text: toutes les postes
            href: posts\index.qmd
          - text: English
            href: posts\en.qmd
          - text: Français
            href: posts\fr.qmd
      - text: Produits
        menu: 
          - text: Voiture
            href: products\auto.qmd
          - text: Maison
            href: products\home.qmd
          - text: Voyage
            href: products\travel.qmd
          - text: Vie
            href: products\life.qmd
          - text: Accident et Santé
            href: products\accident.qmd
          - text: Plan de protection
            href: products\protection_plans.qmd
          - text: Autres produtis et services
            href: products\other_products.qmd
      - text: Assurance
        href: insurance.qmd
      - text: Client(e)
        href: customer.qmd
      - text: Réclamations
        href: claims.qmd
    
    right:
      - text: "Français"
        href: aboutfr.qmd
      - text: "English"
        href: abouten.qmd
  page-footer: 
    left: "Copyright 2024, Made by [Kunal Khurana](https://ilovesoils.com/about.html)"
    right:
      - text: "About iA"
        href: aboutia.qmd
      - text: Contact me
        href: contactme.qmd
      - icon: envelope
        href: mailto:Khuranasoilpau@gmail.com
  

format:
  html:
    smooth-scroll: true
    css: styles.css
    link-external-icon: false
    link-external-newwindow: true
    citations-hover: true
    footnotes-hover: true
    toc: true
    code-link: true
  pdf:
    documentclass: scrreprt
